### ISSUE TITLE
Redesign interface with the goal of having ezt be used in shell scripts that generate batches of templated files

### ISSUE THREAD

**Issue by camratchford** [camratchford/easy-template#19]
For example:
- We want to make a shell script that creates 3 ansible plays based on a jinja template.
- We provide it a variable file, and an inline variable that is the loop variable $i.
- We use the loop variable to name the output file and as select logic from within the variable file.

> Shell Script
```bash
for i in staging-1 dns-1 dns-2; do
  ezt --var-file=vars.yml -v "host=${i}" -t build_container.yml.j2 -o "plays/build_${i}.yml"
done
```

> vars.yml
```yaml
hosts:
  staging-1:
    container_host: lxdhost-1
  dns-1:
    container_host: lxdhost-1
  dns-2: 
    container_host: lxdhost-2
```

> build_container.yml.j2
```yaml
---
- name: Build  {{ host }} container
  hosts: {{ hosts[host].container_host }}
  var_files: /opt/monorepo/ansible/inventories/host_vars/{{ host }}.yml
  tasks:
    - name: Provision LXD container
      include_role:
        name: lxd-lifecycle
        tasks_from: build.yml
```
